### ISSUE TITLE
Is OpenBTS only works with 3.0 ?? Supper Speed Error

### ISSUE THREAD

**Issue by junaid124** [Nuand/OpenBTS#5]
Hi 
I am running BladeRF on USB 2.0 because my Laptop USB3.0 doesn't detect BladeRF. every this works fine on USB 3.0 except BladeRF i don't know why.

Is OpenBTS supports only available for USB 2.0?i means while running OpenBTS on BladeRF i got following error.
Error 
"bladeRF transceiver only supports SuperSpeed mode at the moment"  
 
1394732550.318998 14035319428032: 
Starting the system...
ALERT 140353109428032 22:42:35.3 TRXManager.cpp:434:powerOff: POWEROFF failed with status -1
Using internal clock reference
EMERG 140373092689728 22:42:36.6 bladeRFDevice.cpp:100:open: bladeRF transceiver only supports SuperSpeed mode at the moment
ALERT 140373092689728 22:42:36.6 runTransceiver.cpp:160:main: Transceiver exiting...

EMERG 140353108743936 22:42:36.6 OpenBTS.cpp:156:startTransceiver: Transceiver quit with status 256. Exiting.
Regards 
Junaid

**Comment by Nuand** [comment]
Closing this issue. If we remember correctly, you found that YateBTS is supporting SuperSpeed.
