### ISSUE TITLE
Failed to access peripheral: LIBUSB_ERROR_TIMEOUT

### ISSUE THREAD

**Issue by veranson** [Nuand/OpenBTS#6]
bladeRF-cli version:        0.10.6-git-unknown
libbladeRF version:         0.14.0-git-06776a5-ppasaucy
Firmware version:           1.6.1-git-b7e6642
FPGA version:               0.0.3

veranson@veranson-ThinkPad-X201:~/openbts/openbts/trunk/apps$ sudo ./OpenBTS
ALERT 139796983838528 20:53:34.7 OpenBTS.cpp:375:main: OpenBTS (re)starting, ver TRUNK build date Mar 14 2014
1394816014.717389 139796983838528: 

OpenBTS
Copyright 2008, 2009, 2010 Free Software Foundation, Inc.
Copyright 2010 Kestrel Signal Processing, Inc.
Copyright 2011, 2012, 2013 Range Networks, Inc.
Release TRUNK P formal build date Mar 14 2014 rev
"OpenBTS" is a registered trademark of Range Networks, Inc.

Contributors:
  Range Networks, Inc.:
    David Burgess, Harvind Samra, Donald Kirker, Doug Brown,
    Pat Thompson, Kurtis Heimerl
  Kestrel Signal Processing, Inc.:
    David Burgess, Harvind Samra, Raffi Sevlian, Roshan Baliga
  GNU Radio:
    Johnathan Corgan
  Others:
    Anne Kwong, Jacob Appelbaum, Joshua Lackey, Alon Levy
    Alexander Chemeris, Alberto Escudero-Pascual
Incorporated L/GPL libraries and components:
  libosip2, LGPL, 2.1 Copyright 2001-2007 Aymeric MOIZARD jack@atosc.org
  libortp, LGPL, 2.1 Copyright 2001 Simon MORLAT simon.morlat@linphone.org
  libusb, LGPL 2.1, various copyright holders, www.libusb.org
Incorporated BSD/MIT-style libraries and components:
  A5/1 Pedagogical Implementation, Simplified BSD License, Copyright 1998-1999 Marc Briceno, Ian Goldberg, and David Wagner
Incorporated public domain libraries and components:
  sqlite3, released to public domain 15 Sept 2001, www.sqlite.org

This program comes with ABSOLUTELY NO WARRANTY.

Use of this software may be subject to other legal restrictions,
including patent licensing and radio spectrum licensing.
All users of this software are expected to comply with applicable
regulations and laws.  See the LEGAL file in the source code for
more information.

EMERG 139796983838528 20:53:34.7 SubscriberRegistry.cpp:173:init: /var/lib/asterisk/sqlite3dir does not exist
1394816014.720227 139796983838528: 
Starting the system...
ALERT 139796983838528 20:53:34.7 TRXManager.cpp:595:getFactoryCalibration: READFACTORY failed with status 1
EMERG 140524385609472 20:53:34.7 bladeRFDevice.cpp:443:setRxFreq: set RX freq: 9.002e+08

[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
EMERG 140524385609472 20:53:35.7 bladeRFDevice.cpp:443:setRxFreq: set RX freq: 9.002e+08

[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
ALERT 139796983838528 20:53:36.7 TRXManager.cpp:398:tune: TXTUNE failed with status -1
EMERG 140524385609472 20:53:36.7 bladeRFDevice.cpp:438:setTxFreq: set TX freq: 9.452e+08

[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
ALERT 139796983838528 20:53:37.7 TRXManager.cpp:476:setTSC: SETTSC failed with status -1
EMERG 140524385609472 20:53:37.7 bladeRFDevice.cpp:438:setTxFreq: set TX freq: 9.452e+08

[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
ALERT 139796983838528 20:53:38.7 TRXManager.cpp:514:setMaxDelay: SETMAXDLY failed with status -1
ALERT 139796983838528 20:53:38.7 TRXManager.cpp:525:setRxGain: SETRXGAIN failed with status -1
ALERT 139796983838528 20:53:38.7 TRXManager.cpp:446:powerOn: POWERON failed with status -1
ALERT 139796983838528 20:53:38.7 TRXManager.cpp:464:setPower: SETPOWER failed with status -1
ALERT 139796983838528 20:53:38.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:504:setSlot: SETSLOT failed with status -1
ALERT 139796983838528 20:53:40.7 TRXManager.cpp:464:setPower: SETPOWER failed with status -1
1394816020.751235 139796983838528: 
system ready

1394816020.751322 139796983838528: 
use the OpenBTSCLI utility to access CLI

[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
ALERT 139796926134016 20:53:42.7 TRXManager.cpp:464:setPower: SETPOWER failed with status -1
[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
ALERT 139796926134016 20:53:48.7 TRXManager.cpp:464:setPower: SETPOWER failed with status -1
[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
ALERT 139796926134016 20:53:54.7 TRXManager.cpp:464:setPower: SETPOWER failed with status -1
[ERROR] Failed to access peripheral: LIBUSB_ERROR_TIMEOUT
^Cveranson@veranson-ThinkPad-X201:~/openbts/openbts/trunk/apps$

**Comment by Nuand** [comment]
Closing this issue. This repo is getting marked deprecated, with links to the bladeRF wiki for community maintenance and guides. 

If you still have trouble, please start a thread on the Nuand forums for support.
